# set language to C because python is not supported in Mac. Does not make a
# difference because we install python through conda
language: c

branches:
    only:
        - master

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get.
addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

env:
    global:
        # The following versions are the 'default' for tests, unless
        # overidden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - NUMPY_VERSION=1.10
        - ASTROPY_VERSION=stable
        - CONDA_DEPENDENCIES='pytest pip Cython jinja2 pyyaml scipy matplotlib h5py mock sphinx_rtd_theme'
        - PIP_DEPENDENCIES='emcee corner'

    matrix:
        - PYTHON_VERSION=2.7 SETUP_CMD='egg_info'
        - PYTHON_VERSION=3.3 SETUP_CMD='egg_info'
        - PYTHON_VERSION=3.4 SETUP_CMD='egg_info'
        - PYTHON_VERSION=3.5 SETUP_CMD='egg_info'

matrix:

    include:

        # Try MacOS X
        - os: osx
          env: PYTHON_VERSION=2.7 SETUP_CMD='test'

        # Do a coverage test in Python 2 w/ numpy 1.8 for sherpa.
        - os: linux
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.8
               CONDA_CHANNELS='astropy-ci-extras sherpa'
               CONDA_DEPENDENCIES="$CONDA_DEPENDENCIES sherpa"
               SETUP_CMD='test --coverage'

        # Check for sphinx doc build warnings - we do this first because it
        # may run for a long time
        - os: linux
          env: PYTHON_VERSION=2.7 SETUP_CMD='build_sphinx -w'

        # Run examples, do it first as well as it may take some time
        - os: linux
          env: PYTHON_VERSION=3.5 SETUP_CMD='examples'

        # Try Astropy development version
        - os: linux
          env: PYTHON_VERSION=2.7 ASTROPY_VERSION=development SETUP_CMD='test'
        - os: linux
          env: PYTHON_VERSION=3.5 ASTROPY_VERSION=development SETUP_CMD='test'

        # Try all python versions
        - os: linux
          env: PYTHON_VERSION=2.7 SETUP_CMD='test'
        - os: linux
          env: PYTHON_VERSION=3.3 SETUP_CMD='test' NUMPY_VERSION=1.9
        - os: linux
          env: PYTHON_VERSION=3.4 SETUP_CMD='test'
        - os: linux
          env: PYTHON_VERSION=3.5 SETUP_CMD='test'

        # Try other numpy versions (1.8 is tested by sherpa)
        - os: linux
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.7 SETUP_CMD='test'
        - os: linux
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.9 SETUP_CMD='test'

before_install:
    # If there are matplotlib tests, comment these out to
    # Make sure that interactive matplotlib backends work
    #- export DISPLAY=:99.0
    #- sh -e /etc/init.d/xvfb start

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

script:
   - |
     if [[ $SETUP_CMD == 'examples' ]]; then 
         python setup.py install
         cd examples
         echo 'backend : Agg' > matplotlibrc
         for script in RXJ1713*.py; do
             echo ''
             echo "Running example $script..."
             time python $script
         done
     else
         python setup.py $SETUP_CMD
     fi

after_success:
    # Uncomment line below if coveralls.io is set up for this package.
    - if [[ $SETUP_CMD == *coverage* ]]; then coveralls --rcfile='naima/tests/coveragerc'; fi
